import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { hmacHex, safeEqual } from '../lib/tokens';

/**
 * Private file storage for prescription uploads. Files are never served
 * from a public path; reading one needs a short-lived signed URL.
 */
export interface StorageProvider {
  put(key: string, data: Buffer): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

/** Keys are generated by us: a folder, a random id and a known extension. */
const KEY_PATTERN = /^[a-z]+\/[0-9a-f-]{36}\.(jpg|png|webp|pdf)$/;

export function assertStorageKey(key: string): void {
  if (!KEY_PATTERN.test(key)) throw new Error(`Invalid storage key: ${key}`);
}

/** Local disk, outside any web root, with owner-only file permissions. */
export class LocalDiskStorage implements StorageProvider {
  private readonly root: string;

  constructor(root: string) {
    this.root = resolve(root);
  }

  private path(key: string): string {
    assertStorageKey(key);
    return join(this.root, key);
  }

  async put(key: string, data: Buffer): Promise<void> {
    const path = this.path(key);
    await mkdir(dirname(path), { recursive: true, mode: 0o700 });
    await writeFile(path, data, { mode: 0o600, flag: 'wx' });
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.path(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}

/** Signed, expiring links to a stored file: `?expires=<unix seconds>&signature=<hex>`. */
export class FileLinks {
  constructor(
    private readonly secret: string,
    private readonly baseUrl: string,
  ) {}

  private signature(key: string, expires: number): string {
    return hmacHex(this.secret, `file:${key}:${expires}`);
  }

  url(key: string, ttlSeconds = 300, now = Date.now()): string {
    const expires = Math.floor(now / 1000) + ttlSeconds;
    const query = new URLSearchParams({
      expires: String(expires),
      signature: this.signature(key, expires),
    });
    return `${this.baseUrl}/v1/files/${key}?${query.toString()}`;
  }

  verify(key: string, expires: number, signature: string, now = Date.now()): boolean {
    if (expires < Math.floor(now / 1000)) return false;
    return safeEqual(this.signature(key, expires), signature);
  }
}
