import type { AddressConfig } from './address';

/**
 * India: states and union territories, and which region a PIN code belongs
 * to. A PIN's first two or three digits identify its postal circle; the
 * longest matching prefix wins. Major cities are listed by their sorting
 * district so the city can be pre-filled too. The lookup only pre-fills the
 * form: customers can always correct it, so an edge case is an
 * inconvenience, not a wrong delivery.
 */
const regions = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
] as const;

type Region = (typeof regions)[number];

/** [prefix, region] by postal circle. */
const circles: [string, Region][] = [
  ['11', 'Delhi'],
  ['12', 'Haryana'],
  ['13', 'Haryana'],
  ['14', 'Punjab'],
  ['15', 'Punjab'],
  ['16', 'Punjab'],
  ['160', 'Chandigarh'],
  ['17', 'Himachal Pradesh'],
  ['18', 'Jammu and Kashmir'],
  ['19', 'Jammu and Kashmir'],
  ['194', 'Ladakh'],
  ['20', 'Uttar Pradesh'],
  ['21', 'Uttar Pradesh'],
  ['22', 'Uttar Pradesh'],
  ['23', 'Uttar Pradesh'],
  ['24', 'Uttar Pradesh'],
  ['246', 'Uttarakhand'],
  ['247', 'Uttarakhand'],
  ['248', 'Uttarakhand'],
  ['249', 'Uttarakhand'],
  ['25', 'Uttar Pradesh'],
  ['26', 'Uttar Pradesh'],
  ['262', 'Uttarakhand'],
  ['263', 'Uttarakhand'],
  ['27', 'Uttar Pradesh'],
  ['28', 'Uttar Pradesh'],
  ['30', 'Rajasthan'],
  ['31', 'Rajasthan'],
  ['32', 'Rajasthan'],
  ['33', 'Rajasthan'],
  ['34', 'Rajasthan'],
  ['36', 'Gujarat'],
  ['37', 'Gujarat'],
  ['38', 'Gujarat'],
  ['39', 'Gujarat'],
  ['396', 'Dadra and Nagar Haveli and Daman and Diu'],
  ['40', 'Maharashtra'],
  ['403', 'Goa'],
  ['41', 'Maharashtra'],
  ['42', 'Maharashtra'],
  ['43', 'Maharashtra'],
  ['44', 'Maharashtra'],
  ['45', 'Madhya Pradesh'],
  ['46', 'Madhya Pradesh'],
  ['47', 'Madhya Pradesh'],
  ['48', 'Madhya Pradesh'],
  ['49', 'Chhattisgarh'],
  ['50', 'Telangana'],
  ['51', 'Andhra Pradesh'],
  ['52', 'Andhra Pradesh'],
  ['53', 'Andhra Pradesh'],
  ['56', 'Karnataka'],
  ['57', 'Karnataka'],
  ['58', 'Karnataka'],
  ['59', 'Karnataka'],
  ['60', 'Tamil Nadu'],
  ['605', 'Puducherry'],
  ['61', 'Tamil Nadu'],
  ['62', 'Tamil Nadu'],
  ['63', 'Tamil Nadu'],
  ['64', 'Tamil Nadu'],
  ['67', 'Kerala'],
  ['68', 'Kerala'],
  ['682', 'Kerala'],
  ['69', 'Kerala'],
  ['70', 'West Bengal'],
  ['71', 'West Bengal'],
  ['72', 'West Bengal'],
  ['73', 'West Bengal'],
  ['737', 'Sikkim'],
  ['74', 'West Bengal'],
  ['744', 'Andaman and Nicobar Islands'],
  ['75', 'Odisha'],
  ['76', 'Odisha'],
  ['77', 'Odisha'],
  ['78', 'Assam'],
  ['790', 'Arunachal Pradesh'],
  ['791', 'Arunachal Pradesh'],
  ['792', 'Arunachal Pradesh'],
  ['793', 'Meghalaya'],
  ['794', 'Meghalaya'],
  ['795', 'Manipur'],
  ['796', 'Mizoram'],
  ['797', 'Nagaland'],
  ['798', 'Nagaland'],
  ['799', 'Tripura'],
  ['80', 'Bihar'],
  ['81', 'Jharkhand'],
  ['82', 'Jharkhand'],
  ['83', 'Jharkhand'],
  ['84', 'Bihar'],
  ['85', 'Bihar'],
];

/** [prefix, city] for major sorting districts. */
const cities: [string, string][] = [
  ['110', 'New Delhi'],
  ['122', 'Gurugram'],
  ['160', 'Chandigarh'],
  ['226', 'Lucknow'],
  ['248', 'Dehradun'],
  ['302', 'Jaipur'],
  ['380', 'Ahmedabad'],
  ['395', 'Surat'],
  ['400', 'Mumbai'],
  ['403', 'Panaji'],
  ['411', 'Pune'],
  ['440', 'Nagpur'],
  ['452', 'Indore'],
  ['462', 'Bhopal'],
  ['500', 'Hyderabad'],
  ['520', 'Vijayawada'],
  ['530', 'Visakhapatnam'],
  ['560', 'Bengaluru'],
  ['570', 'Mysuru'],
  ['600', 'Chennai'],
  ['641', 'Coimbatore'],
  ['682', 'Kochi'],
  ['695', 'Thiruvananthapuram'],
  ['700', 'Kolkata'],
  ['751', 'Bhubaneswar'],
  ['781', 'Guwahati'],
  ['800', 'Patna'],
  ['834', 'Ranchi'],
];

export const indiaAddress: AddressConfig = {
  regionLabel: 'State',
  regions,
  phone: { dialCode: '+91', pattern: '^[6-9][0-9]{9}$', example: '98765 43210' },
  postalLookup: [
    ...circles.map(([prefix, region]) => ({ prefix, region, city: null })),
    ...cities.map(([prefix, city]) => {
      const region = circles
        .filter(([circle]) => prefix.startsWith(circle))
        .sort((a, b) => b[0].length - a[0].length)[0]?.[1];
      if (!region) throw new Error(`No postal circle for city prefix ${prefix}`);
      return { prefix, region, city };
    }),
  ],
};
