import type {
  CategorySlug,
  FrameFit,
  FrameMaterial,
  FrameShape,
  RimType,
} from '@optical/shared/catalog';
import type { ColourwayCode, SunTintCode } from './colourways';

/**
 * The launch frame range. Measurements are in millimetres, in the order
 * printed on a temple arm: lens width, bridge, temple length; then lens
 * height and total front width. Prices are whole rupees, tax-inclusive.
 */
export interface FrameModel {
  name: string;
  category: Exclude<CategorySlug, 'accessories'>;
  shape: FrameShape;
  material: FrameMaterial;
  rim: RimType;
  fit: FrameFit;
  /** [lens width, bridge, temple, lens height, total width] */
  mm: readonly [number, number, number, number, number];
  weightG: number;
  price: number;
  /** Eyeglass colourways, or [colourway, lens tint] pairs for sunglasses. */
  colours: readonly (ColourwayCode | readonly [ColourwayCode, SunTintCode])[];
  tags: readonly string[];
  /** One sentence that is only true of this frame. */
  line: string;
  springHinges?: boolean;
  /** Days since launch; under 45 shows as new. */
  launchedDaysAgo: number;
  popularity: number;
}

type Row = Omit<FrameModel, 'category'>;
const eyeglasses = (rows: Row[]) =>
  rows.map((row) => ({ ...row, category: 'eyeglasses' as const }));
const sunglasses = (rows: Row[]) =>
  rows.map((row) => ({ ...row, category: 'sunglasses' as const }));
const computer = (rows: Row[]) =>
  rows.map((row) => ({ ...row, category: 'computer-glasses' as const }));
const kids = (rows: Row[]) => rows.map((row) => ({ ...row, category: 'kids' as const }));

export const frameModels: FrameModel[] = [
  ...eyeglasses([
    {
      name: 'Harbour',
      shape: 'round',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [48, 21, 145, 44, 131],
      weightG: 21,
      price: 2490,
      colours: ['jet-black', 'havana', 'crystal', 'sage'],
      tags: ['classic', 'minimal'],
      line: 'A soft keyhole bridge sits low on the nose, so the lenses centre well on most faces.',
      springHinges: true,
      launchedDaysAgo: 400,
      popularity: 96,
    },
    {
      name: 'Linden',
      shape: 'rectangle',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'men',
      mm: [54, 18, 145, 38, 140],
      weightG: 24,
      price: 2290,
      colours: ['matte-black', 'espresso', 'navy', 'smoke'],
      tags: ['everyday', 'professional'],
      line: 'Clean straight lines and a slightly thicker brow for a steady, business-like look.',
      launchedDaysAgo: 380,
      popularity: 91,
    },
    {
      name: 'Marlow',
      shape: 'square',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [51, 20, 145, 43, 136],
      weightG: 25,
      price: 2790,
      colours: ['jet-black', 'havana', 'sand', 'wine'],
      tags: ['bold', 'classic'],
      line: 'Chunky 5 mm acetate with softened corners: confident without being loud.',
      launchedDaysAgo: 300,
      popularity: 88,
    },
    {
      name: 'Ives',
      shape: 'wayfarer',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [52, 19, 145, 41, 138],
      weightG: 26,
      price: 2690,
      colours: ['jet-black', 'havana', 'navy', 'grey-fade'],
      tags: ['classic', 'bold'],
      line: 'The familiar trapezoid, cut a little slimmer through the brow for everyday wear.',
      launchedDaysAgo: 360,
      popularity: 90,
    },
    {
      name: 'Juniper',
      shape: 'cat-eye',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'women',
      mm: [52, 17, 140, 40, 136],
      weightG: 20,
      price: 2890,
      colours: ['jet-black', 'blonde-tortoise', 'rose-crystal', 'wine'],
      tags: ['statement', 'retro'],
      line: 'A gentle lift at the outer corner, more wing than point.',
      launchedDaysAgo: 250,
      popularity: 86,
    },
    {
      name: 'Calder',
      shape: 'browline',
      material: 'mixed',
      rim: 'full-rim',
      fit: 'men',
      mm: [51, 20, 145, 42, 137],
      weightG: 23,
      price: 3290,
      colours: ['black-gold', 'havana-gold', 'espresso-gold'],
      tags: ['retro', 'professional'],
      line: 'An acetate brow over a fine metal lower rim, the mid-century classic.',
      launchedDaysAgo: 320,
      popularity: 80,
    },
    {
      name: 'Wren',
      shape: 'round',
      material: 'metal',
      rim: 'full-rim',
      fit: 'women',
      mm: [47, 20, 140, 43, 128],
      weightG: 14,
      price: 2990,
      colours: ['gold', 'silver', 'rose-gold', 'gunmetal'],
      tags: ['minimal', 'lightweight'],
      line: 'Wire-thin round rims and adjustable pads that barely register once they are on.',
      launchedDaysAgo: 290,
      popularity: 84,
    },
    {
      name: 'Soren',
      shape: 'rectangle',
      material: 'titanium',
      rim: 'full-rim',
      fit: 'men',
      mm: [53, 18, 145, 36, 138],
      weightG: 11,
      price: 6490,
      colours: ['gunmetal', 'silver', 'matte-black-metal'],
      tags: ['lightweight', 'professional', 'premium'],
      line: 'Beta-titanium throughout, 11 g, with temples that flex instead of snapping.',
      launchedDaysAgo: 210,
      popularity: 78,
    },
    {
      name: 'Tamsin',
      shape: 'hexagon',
      material: 'metal',
      rim: 'full-rim',
      fit: 'women',
      mm: [50, 20, 140, 45, 132],
      weightG: 15,
      price: 3190,
      colours: ['gold', 'rose-gold', 'silver'],
      tags: ['statement', 'minimal'],
      line: 'Six soft facets that catch the light without looking angular.',
      launchedDaysAgo: 30,
      popularity: 75,
    },
    {
      name: 'Arlo',
      shape: 'square',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [52, 18, 145, 42, 137],
      weightG: 16,
      price: 1690,
      colours: ['matte-black', 'navy', 'sage', 'smoke'],
      tags: ['everyday', 'lightweight', 'durable'],
      line: 'Flexible TR90 that bends back into shape, at a price that makes a spare pair easy.',
      springHinges: true,
      launchedDaysAgo: 420,
      popularity: 93,
    },
    {
      name: 'Kestrel',
      shape: 'aviator',
      material: 'metal',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [56, 15, 145, 48, 138],
      weightG: 18,
      price: 3490,
      colours: ['gold', 'silver', 'gunmetal'],
      tags: ['classic', 'retro'],
      line: 'A double-bridge aviator scaled for clear lenses and daily wear.',
      launchedDaysAgo: 330,
      popularity: 82,
    },
    {
      name: 'Orla',
      shape: 'cat-eye',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'women',
      mm: [53, 16, 140, 41, 136],
      weightG: 22,
      price: 3290,
      colours: ['havana', 'jet-black', 'honey-fade', 'rose-crystal'],
      tags: ['statement', 'retro'],
      line: 'A sharper upsweep than Juniper, with a bevelled front that adds depth.',
      launchedDaysAgo: 20,
      popularity: 79,
    },
    {
      name: 'Pascal',
      shape: 'round',
      material: 'titanium',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [46, 22, 145, 42, 128],
      weightG: 9,
      price: 5990,
      colours: ['gold', 'silver', 'gunmetal'],
      tags: ['lightweight', 'premium', 'minimal'],
      line: 'Our lightest round at 9 g, with a raised bridge that suits lower nose bridges.',
      launchedDaysAgo: 180,
      popularity: 74,
    },
    {
      name: 'Quill',
      shape: 'rectangle',
      material: 'metal',
      rim: 'half-rim',
      fit: 'men',
      mm: [55, 17, 145, 34, 140],
      weightG: 16,
      price: 2790,
      colours: ['gunmetal', 'silver', 'matte-black-metal'],
      tags: ['professional', 'minimal'],
      line: 'A half-rim that keeps the top line strong and leaves the lower edge open.',
      launchedDaysAgo: 340,
      popularity: 72,
    },
    {
      name: 'Rowan',
      shape: 'square',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'men',
      mm: [54, 19, 150, 45, 142],
      weightG: 28,
      price: 3490,
      colours: ['matte-black', 'havana', 'espresso', 'navy'],
      tags: ['bold'],
      line: 'A wide, deep square with 150 mm temples, made for larger faces.',
      launchedDaysAgo: 260,
      popularity: 77,
    },
    {
      name: 'Sable',
      shape: 'wayfarer',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [50, 20, 145, 40, 134],
      weightG: 23,
      price: 2490,
      colours: ['jet-black', 'havana', 'crystal', 'sage'],
      tags: ['classic', 'everyday'],
      line: 'A compact wayfarer for narrower faces that find the original too wide.',
      launchedDaysAgo: 390,
      popularity: 85,
    },
    {
      name: 'Tove',
      shape: 'round',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'women',
      mm: [45, 21, 140, 42, 124],
      weightG: 18,
      price: 2290,
      colours: ['blonde-tortoise', 'rose-crystal', 'crystal', 'wine'],
      tags: ['minimal', 'retro'],
      line: 'A small, soft round in translucent acetate that lets your skin tone through.',
      launchedDaysAgo: 150,
      popularity: 73,
    },
    {
      name: 'Ulla',
      shape: 'hexagon',
      material: 'titanium',
      rim: 'rimless',
      fit: 'women',
      mm: [50, 19, 140, 40, 130],
      weightG: 7,
      price: 7490,
      colours: ['gold', 'silver', 'rose-gold'],
      tags: ['lightweight', 'premium', 'minimal'],
      line: 'Rimless hexagonal lenses on titanium hardware, 7 g in total.',
      launchedDaysAgo: 10,
      popularity: 70,
    },
    {
      name: 'Vale',
      shape: 'rectangle',
      material: 'titanium',
      rim: 'rimless',
      fit: 'men',
      mm: [54, 17, 145, 36, 138],
      weightG: 8,
      price: 7990,
      colours: ['gunmetal', 'silver', 'gold'],
      tags: ['lightweight', 'premium', 'professional'],
      line: 'Nearly invisible rimless rectangles for when you want the glasses to disappear.',
      launchedDaysAgo: 200,
      popularity: 71,
    },
    {
      name: 'Wilder',
      shape: 'browline',
      material: 'mixed',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [50, 21, 145, 41, 135],
      weightG: 22,
      price: 3490,
      colours: ['black-gold', 'havana-gold', 'navy-silver'],
      tags: ['retro', 'statement'],
      line: 'A rounder browline with a sculpted brow that follows the eyebrow line.',
      launchedDaysAgo: 40,
      popularity: 76,
    },
    {
      name: 'Yara',
      shape: 'cat-eye',
      material: 'metal',
      rim: 'full-rim',
      fit: 'women',
      mm: [52, 17, 140, 40, 134],
      weightG: 14,
      price: 3290,
      colours: ['gold', 'rose-gold', 'silver'],
      tags: ['minimal', 'statement'],
      line: 'The cat-eye line drawn in fine metal, lighter on the face than acetate.',
      launchedDaysAgo: 270,
      popularity: 74,
    },
    {
      name: 'Ansel',
      shape: 'round',
      material: 'metal',
      rim: 'full-rim',
      fit: 'men',
      mm: [49, 21, 145, 45, 132],
      weightG: 15,
      price: 2990,
      colours: ['gunmetal', 'gold', 'silver'],
      tags: ['classic', 'retro'],
      line: 'A scholarly round with a slim saddle bridge and acetate temple tips.',
      launchedDaysAgo: 310,
      popularity: 81,
    },
    {
      name: 'Bexley',
      shape: 'rectangle',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'women',
      mm: [52, 17, 140, 36, 134],
      weightG: 19,
      price: 2490,
      colours: ['wine', 'havana', 'rose-crystal', 'jet-black'],
      tags: ['everyday', 'professional'],
      line: 'A slim rectangle with a subtle lift at the brow for a softer finish.',
      launchedDaysAgo: 230,
      popularity: 78,
    },
    {
      name: 'Cove',
      shape: 'square',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [49, 21, 145, 44, 132],
      weightG: 22,
      price: 2690,
      colours: ['sage', 'crystal', 'havana', 'jet-black'],
      tags: ['everyday', 'minimal'],
      line: 'A rounded square in a medium width, the easy middle of the range.',
      launchedDaysAgo: 350,
      popularity: 87,
    },
    {
      name: 'Dune',
      shape: 'wayfarer',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [53, 18, 145, 42, 139],
      weightG: 15,
      price: 1590,
      colours: ['matte-black', 'navy', 'espresso'],
      tags: ['everyday', 'durable', 'lightweight'],
      line: 'A wayfarer in bendable TR90, for bags, sofas and small children.',
      springHinges: true,
      launchedDaysAgo: 410,
      popularity: 89,
    },
    {
      name: 'Elm',
      shape: 'rectangle',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'men',
      mm: [55, 18, 145, 37, 141],
      weightG: 14,
      price: 1490,
      colours: ['matte-black', 'smoke', 'navy'],
      tags: ['everyday', 'lightweight', 'durable'],
      line: 'Our most affordable frame, with the same lenses and warranty as the rest.',
      springHinges: true,
      launchedDaysAgo: 430,
      popularity: 92,
    },
    {
      name: 'Fenn',
      shape: 'hexagon',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [50, 20, 145, 44, 134],
      weightG: 21,
      price: 2890,
      colours: ['havana', 'crystal', 'jet-black', 'sand'],
      tags: ['statement'],
      line: 'A hexagon in thick acetate, geometric but warm.',
      launchedDaysAgo: 25,
      popularity: 69,
    },
    {
      name: 'Gale',
      shape: 'aviator',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [55, 16, 145, 47, 138],
      weightG: 24,
      price: 3190,
      colours: ['havana', 'jet-black', 'smoke'],
      tags: ['retro', 'bold'],
      line: 'The aviator teardrop in acetate, with a keyhole bridge instead of a double bar.',
      launchedDaysAgo: 190,
      popularity: 72,
    },
    {
      name: 'Hollis',
      shape: 'square',
      material: 'metal',
      rim: 'full-rim',
      fit: 'men',
      mm: [52, 19, 145, 44, 136],
      weightG: 16,
      price: 3190,
      colours: ['gunmetal', 'gold', 'matte-black-metal'],
      tags: ['professional', 'minimal'],
      line: 'A square in brushed stainless steel with adjustable nose pads.',
      launchedDaysAgo: 280,
      popularity: 75,
    },
    {
      name: 'Isla',
      shape: 'round',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'women',
      mm: [50, 19, 140, 47, 132],
      weightG: 20,
      price: 2790,
      colours: ['havana', 'rose-crystal', 'honey-fade', 'crystal'],
      tags: ['retro', 'statement'],
      line: 'A tall round with room for progressive lenses, which many rounds lack.',
      launchedDaysAgo: 170,
      popularity: 76,
    },
    {
      name: 'Juno',
      shape: 'cat-eye',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'women',
      mm: [51, 17, 140, 39, 133],
      weightG: 13,
      price: 1790,
      colours: ['jet-black', 'wine', 'rose-crystal'],
      tags: ['everyday', 'lightweight'],
      line: 'An everyday cat-eye in light TR90, gentle enough for first-time wearers.',
      springHinges: true,
      launchedDaysAgo: 220,
      popularity: 80,
    },
    {
      name: 'Koa',
      shape: 'rectangle',
      material: 'acetate',
      rim: 'half-rim',
      fit: 'men',
      mm: [54, 18, 145, 36, 139],
      weightG: 20,
      price: 2690,
      colours: ['jet-black', 'havana', 'navy'],
      tags: ['professional'],
      line: 'An acetate brow with an open lower edge, lighter-looking than a full rim.',
      launchedDaysAgo: 240,
      popularity: 68,
    },
    {
      name: 'Lark',
      shape: 'rectangle',
      material: 'titanium',
      rim: 'half-rim',
      fit: 'women',
      mm: [51, 17, 140, 27, 132],
      weightG: 10,
      price: 6990,
      colours: ['rose-gold', 'gold', 'silver'],
      tags: ['lightweight', 'premium'],
      line: 'A slim titanium half-rim, 27 mm deep, made for single-vision and reading lenses.',
      launchedDaysAgo: 35,
      popularity: 66,
    },
    {
      name: 'Mira',
      shape: 'square',
      material: 'titanium',
      rim: 'full-rim',
      fit: 'women',
      mm: [50, 18, 140, 42, 131],
      weightG: 10,
      price: 6990,
      colours: ['gold', 'silver', 'rose-gold'],
      tags: ['lightweight', 'premium', 'minimal'],
      line: 'A soft titanium square at 10 g, hypoallergenic and nickel-free.',
      launchedDaysAgo: 160,
      popularity: 70,
    },
    {
      name: 'Nash',
      shape: 'wayfarer',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'men',
      mm: [55, 19, 150, 44, 145],
      weightG: 30,
      price: 3290,
      colours: ['matte-black', 'havana', 'espresso'],
      tags: ['bold'],
      line: 'A wide wayfarer with 150 mm temples, for broader faces.',
      launchedDaysAgo: 250,
      popularity: 71,
    },
    {
      name: 'Otis',
      shape: 'round',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'men',
      mm: [52, 22, 150, 49, 142],
      weightG: 27,
      price: 3290,
      colours: ['jet-black', 'havana', 'smoke'],
      tags: ['bold', 'retro'],
      line: 'A large, deep round in heavy acetate: the intellectual, scaled up.',
      launchedDaysAgo: 140,
      popularity: 69,
    },
  ]),
  ...sunglasses([
    {
      name: 'Pike',
      shape: 'aviator',
      material: 'metal',
      rim: 'full-rim',
      fit: 'men',
      mm: [58, 14, 140, 50, 140],
      weightG: 20,
      price: 3990,
      colours: [
        ['gold', 'green'],
        ['silver', 'grey'],
        ['gunmetal', 'grey'],
        ['gold', 'brown'],
      ],
      tags: ['classic', 'outdoor'],
      line: 'The pilot shape at full size, with deep lenses that cover the whole eye.',
      launchedDaysAgo: 360,
      popularity: 94,
    },
    {
      name: 'Reed',
      shape: 'wayfarer',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [52, 20, 145, 42, 140],
      weightG: 28,
      price: 3490,
      colours: [
        ['jet-black', 'green'],
        ['havana', 'brown'],
        ['navy', 'grey'],
      ],
      tags: ['classic', 'outdoor'],
      line: 'A sun wayfarer with a stronger forward tilt to keep glare off the lens.',
      launchedDaysAgo: 380,
      popularity: 92,
    },
    {
      name: 'Sol',
      shape: 'round',
      material: 'metal',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [50, 22, 145, 48, 134],
      weightG: 16,
      price: 3290,
      colours: [
        ['gold', 'brown'],
        ['silver', 'grey'],
        ['rose-gold', 'rose'],
      ],
      tags: ['retro', 'minimal'],
      line: 'Round metal sunglasses with a high bridge, easy to wear on warm days.',
      launchedDaysAgo: 300,
      popularity: 83,
    },
    {
      name: 'Teo',
      shape: 'square',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'men',
      mm: [54, 19, 145, 47, 142],
      weightG: 30,
      price: 3790,
      colours: [
        ['matte-black', 'grey'],
        ['havana', 'brown'],
        ['sand', 'brown'],
      ],
      tags: ['bold', 'outdoor'],
      line: 'A thick square with deep lenses for broad, bright days.',
      launchedDaysAgo: 210,
      popularity: 80,
    },
    {
      name: 'Umber',
      shape: 'cat-eye',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'women',
      mm: [55, 17, 140, 45, 142],
      weightG: 26,
      price: 3990,
      colours: [
        ['jet-black', 'grey'],
        ['havana', 'brown'],
        ['wine', 'rose'],
      ],
      tags: ['statement', 'retro'],
      line: 'An oversized cat-eye with a dramatic sweep, softened by rounded lower lenses.',
      launchedDaysAgo: 28,
      popularity: 82,
    },
    {
      name: 'Vesper',
      shape: 'hexagon',
      material: 'metal',
      rim: 'full-rim',
      fit: 'women',
      mm: [54, 19, 140, 50, 138],
      weightG: 18,
      price: 3690,
      colours: [
        ['gold', 'green'],
        ['rose-gold', 'rose'],
        ['silver', 'blue'],
      ],
      tags: ['statement'],
      line: 'Large faceted lenses in fine metal, with a brow bar across the top.',
      launchedDaysAgo: 150,
      popularity: 73,
    },
    {
      name: 'Wynn',
      shape: 'rectangle',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [56, 17, 145, 40, 142],
      weightG: 26,
      price: 3190,
      colours: [
        ['jet-black', 'grey'],
        ['havana', 'brown'],
        ['smoke', 'grey'],
      ],
      tags: ['everyday'],
      line: 'A sleek rectangle that sits close to the face, good for driving.',
      launchedDaysAgo: 260,
      popularity: 78,
    },
    {
      name: 'Zephyr',
      shape: 'aviator',
      material: 'titanium',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [57, 15, 140, 49, 140],
      weightG: 13,
      price: 6490,
      colours: [
        ['gold', 'green'],
        ['silver', 'grey'],
        ['gunmetal', 'blue'],
      ],
      tags: ['premium', 'lightweight', 'outdoor'],
      line: 'A titanium aviator at 13 g, light enough to forget on long drives.',
      launchedDaysAgo: 15,
      popularity: 76,
    },
    {
      name: 'Bay',
      shape: 'browline',
      material: 'mixed',
      rim: 'full-rim',
      fit: 'men',
      mm: [53, 20, 145, 45, 140],
      weightG: 25,
      price: 3990,
      colours: [
        ['black-gold', 'green'],
        ['havana-gold', 'brown'],
      ],
      tags: ['retro'],
      line: 'The browline as sunglasses, with deep lenses under a strong brow.',
      launchedDaysAgo: 230,
      popularity: 70,
    },
    {
      name: 'Cinder',
      shape: 'wayfarer',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [54, 18, 145, 44, 141],
      weightG: 20,
      price: 2490,
      colours: [
        ['matte-black', 'grey'],
        ['navy', 'blue'],
        ['sage', 'green'],
      ],
      tags: ['durable', 'outdoor', 'lightweight'],
      line: 'Flexible TR90 sunglasses that survive a beach bag.',
      springHinges: true,
      launchedDaysAgo: 340,
      popularity: 86,
    },
    {
      name: 'Delta',
      shape: 'square',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'women',
      mm: [53, 18, 140, 50, 140],
      weightG: 27,
      price: 3890,
      colours: [
        ['havana', 'brown'],
        ['blonde-tortoise', 'brown'],
        ['jet-black', 'grey'],
        ['rose-crystal', 'rose'],
      ],
      tags: ['statement', 'bold'],
      line: 'A tall, soft square with thick temples: glamorous but practical.',
      launchedDaysAgo: 120,
      popularity: 77,
    },
    {
      name: 'Ember',
      shape: 'round',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [49, 21, 145, 47, 134],
      weightG: 23,
      price: 3290,
      colours: [
        ['havana', 'brown'],
        ['jet-black', 'grey'],
        ['honey-fade', 'brown'],
      ],
      tags: ['retro'],
      line: 'Round acetate sunglasses with a keyhole bridge and warm brown lenses.',
      launchedDaysAgo: 190,
      popularity: 74,
    },
    {
      name: 'Fjord',
      shape: 'rectangle',
      material: 'metal',
      rim: 'half-rim',
      fit: 'men',
      mm: [57, 16, 145, 40, 142],
      weightG: 19,
      price: 3490,
      colours: [
        ['gunmetal', 'grey'],
        ['silver', 'blue'],
        ['gold', 'brown'],
      ],
      tags: ['outdoor', 'minimal'],
      line: 'A sporty half-rim that keeps the view below the lens open.',
      launchedDaysAgo: 280,
      popularity: 71,
    },
    {
      name: 'Glade',
      shape: 'cat-eye',
      material: 'metal',
      rim: 'full-rim',
      fit: 'women',
      mm: [54, 17, 140, 46, 138],
      weightG: 16,
      price: 3590,
      colours: [
        ['gold', 'brown'],
        ['rose-gold', 'rose'],
      ],
      tags: ['minimal', 'statement'],
      line: 'A fine metal cat-eye with gradient lenses, dark above and light below.',
      launchedDaysAgo: 22,
      popularity: 72,
    },
    {
      name: 'Haven',
      shape: 'square',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'women',
      mm: [56, 17, 140, 52, 145],
      weightG: 30,
      price: 4290,
      colours: [
        ['jet-black', 'grey'],
        ['havana', 'brown'],
        ['sand', 'brown'],
      ],
      tags: ['statement', 'bold'],
      line: 'Our biggest lenses, for maximum coverage on the brightest days.',
      launchedDaysAgo: 100,
      popularity: 75,
    },
    {
      name: 'Indigo',
      shape: 'aviator',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [57, 15, 145, 50, 142],
      weightG: 27,
      price: 3790,
      colours: [
        ['havana', 'brown'],
        ['jet-black', 'grey'],
        ['navy', 'blue'],
      ],
      tags: ['retro', 'bold'],
      line: 'A thick acetate aviator with a flat brow and blue-tinted option.',
      launchedDaysAgo: 170,
      popularity: 73,
    },
  ]),
  ...computer([
    {
      name: 'Pixel',
      shape: 'rectangle',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [53, 18, 145, 38, 138],
      weightG: 14,
      price: 1790,
      colours: ['matte-black', 'navy', 'smoke'],
      tags: ['everyday', 'lightweight', 'screen'],
      line: 'A light rectangle for long days at a desk, with lenses wide enough for two monitors.',
      springHinges: true,
      launchedDaysAgo: 330,
      popularity: 88,
    },
    {
      name: 'Kernel',
      shape: 'square',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [52, 18, 145, 42, 136],
      weightG: 15,
      price: 1890,
      colours: ['matte-black', 'sage', 'crystal'],
      tags: ['everyday', 'screen'],
      line: 'A rounded square that stays put when you look down at a laptop.',
      springHinges: true,
      launchedDaysAgo: 250,
      popularity: 81,
    },
    {
      name: 'Vector',
      shape: 'round',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [49, 20, 145, 45, 132],
      weightG: 20,
      price: 2290,
      colours: ['jet-black', 'havana', 'crystal'],
      tags: ['classic', 'screen'],
      line: 'A classic round that works as well on video calls as at the screen.',
      launchedDaysAgo: 200,
      popularity: 77,
    },
    {
      name: 'Serif',
      shape: 'wayfarer',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [51, 19, 145, 40, 135],
      weightG: 15,
      price: 1790,
      colours: ['matte-black', 'navy', 'wine'],
      tags: ['everyday', 'screen'],
      line: 'A compact wayfarer with soft pads for all-day comfort.',
      launchedDaysAgo: 18,
      popularity: 74,
    },
    {
      name: 'Cursor',
      shape: 'rectangle',
      material: 'metal',
      rim: 'half-rim',
      fit: 'unisex',
      mm: [54, 17, 145, 35, 138],
      weightG: 15,
      price: 2490,
      colours: ['gunmetal', 'silver'],
      tags: ['professional', 'screen'],
      line: 'A discreet half-rim for the office, with nothing below the lens to catch the eye.',
      launchedDaysAgo: 290,
      popularity: 70,
    },
    {
      name: 'Pane',
      shape: 'hexagon',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'unisex',
      mm: [51, 19, 145, 43, 135],
      weightG: 14,
      price: 1990,
      colours: ['smoke', 'crystal', 'matte-black'],
      tags: ['statement', 'screen'],
      line: 'A lightweight hexagon for people who want their work glasses to have a point of view.',
      launchedDaysAgo: 120,
      popularity: 68,
    },
  ]),
  ...kids([
    {
      name: 'Pip',
      shape: 'round',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'kids',
      mm: [42, 16, 125, 36, 112],
      weightG: 10,
      price: 1290,
      colours: ['berry', 'ocean', 'lime'],
      tags: ['durable', 'lightweight'],
      line: 'A flexible round for ages 4 to 7 that bends rather than breaks.',
      springHinges: true,
      launchedDaysAgo: 310,
      popularity: 85,
    },
    {
      name: 'Tully',
      shape: 'rectangle',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'kids',
      mm: [45, 15, 130, 32, 116],
      weightG: 11,
      price: 1390,
      colours: ['ocean', 'sunset', 'matte-black'],
      tags: ['durable'],
      line: 'A sporty rectangle for ages 7 to 11, with spring hinges for rough mornings.',
      springHinges: true,
      launchedDaysAgo: 280,
      popularity: 80,
    },
    {
      name: 'Bram',
      shape: 'square',
      material: 'acetate',
      rim: 'full-rim',
      fit: 'kids',
      mm: [44, 16, 130, 36, 116],
      weightG: 14,
      price: 1590,
      colours: ['havana', 'navy', 'sunset'],
      tags: ['classic'],
      line: 'A grown-up square in child-sized acetate for ages 8 to 12.',
      launchedDaysAgo: 150,
      popularity: 72,
    },
    {
      name: 'Minnow',
      shape: 'cat-eye',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'kids',
      mm: [43, 15, 125, 34, 112],
      weightG: 10,
      price: 1290,
      colours: ['berry', 'rose-crystal', 'lime'],
      tags: ['durable', 'lightweight'],
      line: 'A tiny cat-eye with a soft lift, light enough for all-day school wear.',
      springHinges: true,
      launchedDaysAgo: 42,
      popularity: 74,
    },
    {
      name: 'Scout',
      shape: 'wayfarer',
      material: 'tr90',
      rim: 'full-rim',
      fit: 'kids',
      mm: [46, 16, 130, 36, 120],
      weightG: 12,
      price: 1490,
      colours: ['ocean', 'matte-black', 'lime'],
      tags: ['durable'],
      line: 'A kids wayfarer with an adjustable strap loop for sport.',
      springHinges: true,
      launchedDaysAgo: 230,
      popularity: 76,
    },
    {
      name: 'Button',
      shape: 'round',
      material: 'metal',
      rim: 'full-rim',
      fit: 'kids',
      mm: [41, 17, 125, 36, 110],
      weightG: 9,
      price: 1790,
      colours: ['gold', 'silver'],
      tags: ['classic', 'lightweight'],
      line: 'A little wire round with soft silicone pads for small noses.',
      launchedDaysAgo: 190,
      popularity: 67,
    },
  ]),
];
